/**
 * Continuity entities — the effects. The entity is described once here; shots point at it from their own records.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useActiveVariationId } from "./storyboard";
import type { CastFacts } from "@/lib/casting/cast";
import { entityFromRow, uniqueKey, type ContinuityEntity, type EntityKind, type EntityPatch, type EntityRow } from "@/lib/continuity/entities";

/** Entities belong to one video variation: the places, props and lights of one video, not of another. */
export const continuityKeys = {
  forProject: (projectId: string, variationId?: string | null) => (variationId ? (["continuity_entities", projectId, variationId] as const) : (["continuity_entities", projectId] as const)),
};

const COLUMNS = "id, project_id, variation_id, kind, key, name, description, constraints, approved_asset_id, reference_asset_ids, archived, created_at, updated_at, cast_role, identity_mode, artist_id";

// the generated database types are regenerated by the host after a migration; until then the table is not in them
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const table = () => (supabase as any).from("continuity_entities");

export async function fetchContinuityEntities(projectId: string, variationId: string): Promise<ContinuityEntity[]> {
  const { data, error } = await table().select(COLUMNS).eq("project_id", projectId).eq("variation_id", variationId).order("created_at", { ascending: true });
  if (error) throw new Error(`could not read the project's continuity entities: ${error.message}`);
  return ((data ?? []) as EntityRow[]).map(entityFromRow).filter((e): e is ContinuityEntity => !!e);
}

/** The active variation's places, props and lighting states. */
export function useContinuityEntities(projectId: string | undefined) {
  const variationId = useActiveVariationId(projectId);
  return useQuery({ queryKey: continuityKeys.forProject(projectId ?? "_none_", variationId ?? "_none_"), queryFn: () => fetchContinuityEntities(projectId!, variationId!), enabled: !!projectId && !!variationId });
}

export async function createContinuityEntity(input: { projectId: string; variationId: string; kind: EntityKind; name: string; description?: string; constraints?: string; takenKeys: readonly string[]; cast?: CastFacts }): Promise<ContinuityEntity> {
  const name = input.name.replace(/\s+/g, " ").trim();
  if (!name) throw new Error("Give it a name first.");
  // The database refuses a character with no role or mode (and a non-character carrying either), so
  // the shape is decided here rather than discovered as a constraint violation.
  if (input.kind === "character" && !input.cast) throw new Error("a character needs a role and an identity mode");
  if (input.kind !== "character" && input.cast) throw new Error(`a ${input.kind} cannot carry casting`);
  const row = {
    project_id: input.projectId, variation_id: input.variationId, kind: input.kind,
    key: uniqueKey(name, input.takenKeys), name,
    description: (input.description ?? "").trim(), constraints: (input.constraints ?? "").trim(),
    ...(input.cast
      ? { cast_role: input.cast.role, identity_mode: input.cast.identityMode, artist_id: input.cast.artistId }
      : {}),
  };
  const { data, error } = await table().insert(row).select(COLUMNS).single();
  if (error) throw new Error(`could not save ${name}: ${error.message}`);
  const entity = entityFromRow(data as EntityRow);
  if (!entity) throw new Error(`could not read ${name} back`);
  return entity;
}

/**
 * Every entity of one variation copied to another (a candidate board must point at the same people, places and
 * lighting states by the same keys, with the same approved pictures). Keys the target already has are skipped;
 * archived ones are left behind. Returns how many were copied. Files are the project's — nothing is duplicated.
 */
export async function copyContinuityEntities(fromVariationId: string, toVariationId: string): Promise<number> {
  const { data: source, error } = await table().select(COLUMNS).eq("variation_id", fromVariationId).eq("archived", false);
  if (error) throw new Error(`could not read the entities to copy: ${error.message}`);
  const { data: existing, error: e2 } = await table().select("key").eq("variation_id", toVariationId);
  if (e2) throw new Error(`could not read the target's entities: ${e2.message}`);
  const taken = new Set(((existing ?? []) as { key: string }[]).map((r) => r.key));
  const rows = ((source ?? []) as EntityRow[])
    .filter((r) => !taken.has(r.key))
    .map((r) => ({
      project_id: r.project_id, variation_id: toVariationId, kind: r.kind, key: r.key, name: r.name,
      description: r.description ?? "", constraints: r.constraints ?? "",
      approved_asset_id: r.approved_asset_id ?? null, reference_asset_ids: r.reference_asset_ids ?? [],
      cast_role: r.cast_role ?? null, identity_mode: r.identity_mode ?? null, artist_id: r.artist_id ?? null,
    }));
  if (rows.length === 0) return 0;
  const { error: e3 } = await table().insert(rows as never);
  if (e3) throw new Error(`could not copy the entities: ${e3.message}`);
  return rows.length;
}

export async function updateContinuityEntity(id: string, patch: EntityPatch): Promise<void> {
  const row: Record<string, unknown> = { updated_at: new Date().toISOString() };
  if (patch.name !== undefined) row.name = patch.name.replace(/\s+/g, " ").trim();
  if (patch.description !== undefined) row.description = patch.description.trim();
  if (patch.constraints !== undefined) row.constraints = patch.constraints.trim();
  if (patch.approvedAssetId !== undefined) row.approved_asset_id = patch.approvedAssetId;
  if (patch.referenceAssetIds !== undefined) row.reference_asset_ids = patch.referenceAssetIds;
  if (patch.archived !== undefined) row.archived = patch.archived;
  if (patch.cast?.role !== undefined) row.cast_role = patch.cast.role;
  if (patch.cast?.identityMode !== undefined) row.identity_mode = patch.cast.identityMode;
  if (patch.cast?.artistId !== undefined) row.artist_id = patch.cast.artistId;
  if (row.name === "") throw new Error("An entity keeps a name.");
  const { error } = await table().update(row).eq("id", id);
  if (error) throw new Error(`could not save the change: ${error.message}`);
}

export function useContinuityMutations(projectId: string) {
  const qc = useQueryClient();
  const variationId = useActiveVariationId(projectId);
  const done = () => qc.invalidateQueries({ queryKey: continuityKeys.forProject(projectId) });
  return {
    create: useMutation({
      mutationFn: (input: Omit<Parameters<typeof createContinuityEntity>[0], "projectId" | "variationId">) => {
        if (!variationId) throw new Error("the project's video variation is not loaded yet");
        return createContinuityEntity({ ...input, projectId, variationId });
      },
      onSuccess: done,
    }),
    update: useMutation({ mutationFn: (input: { id: string; patch: EntityPatch }) => updateContinuityEntity(input.id, input.patch), onSuccess: done }),
  };
}
