/**
 * Scenes — the stretches of one video that wear one outfit (supabase/migrations/20261008220000_outfits_and_scenes.sql).
 * A scene is the director's: a name, a start and an end on the song, and the outfit worn (an entity of kind
 * `outfit`, by key). Shots inside it inherit the outfit (src/lib/wardrobe/outfits.ts resolveOutfit).
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import { useActiveVariationId } from "./storyboard";
import { sceneFromRow, type Scene, type SceneRow } from "@/lib/wardrobe/outfits";

export const scenesKeys = {
  forVariation: (projectId: string, variationId?: string | null) =>
    variationId
      ? (["variation_scenes", projectId, variationId] as const)
      : (["variation_scenes", projectId] as const),
};

const COLUMNS =
  "id, project_id, variation_id, name, start_seconds, end_seconds, outfit_key, notes, created_at, updated_at";
// the generated database types are regenerated by the host after a migration; until then the table is not in them
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const table = () => (supabase as any).from("variation_scenes");

export async function fetchScenes(projectId: string, variationId: string): Promise<Scene[]> {
  const { data, error } = await table()
    .select(COLUMNS)
    .eq("project_id", projectId)
    .eq("variation_id", variationId)
    .order("start_seconds", { ascending: true });
  if (error) throw new Error(`could not read the video's scenes: ${error.message}`);
  return ((data ?? []) as SceneRow[]).map(sceneFromRow);
}

export function useScenes(projectId: string | undefined) {
  const variationId = useActiveVariationId(projectId);
  return useQuery({
    queryKey: scenesKeys.forVariation(projectId ?? "_none_", variationId ?? "_none_"),
    queryFn: () => fetchScenes(projectId!, variationId!),
    enabled: !!projectId && !!variationId,
  });
}

export type SceneWrite = {
  name: string;
  start: number;
  end: number;
  outfitKey: string | null;
  notes?: string;
};

export async function createScene(
  input: SceneWrite & { projectId: string; variationId: string },
): Promise<Scene> {
  const name = input.name.replace(/\s+/g, " ").trim();
  if (!name) throw new Error("Give the scene a name first.");
  if (!(input.end > input.start)) throw new Error("A scene ends after it starts.");
  const row = {
    project_id: input.projectId,
    variation_id: input.variationId,
    name,
    start_seconds: input.start,
    end_seconds: input.end,
    outfit_key: input.outfitKey,
    notes: (input.notes ?? "").trim(),
  };
  const { data, error } = await table().insert(row).select(COLUMNS).single();
  if (error) throw new Error(`could not save the scene ${name}: ${error.message}`);
  return sceneFromRow(data as SceneRow);
}

export async function updateScene(id: string, patch: Partial<SceneWrite>): Promise<void> {
  const row: Record<string, unknown> = {};
  if (patch.name !== undefined) row.name = patch.name.replace(/\s+/g, " ").trim();
  if (patch.start !== undefined) row.start_seconds = patch.start;
  if (patch.end !== undefined) row.end_seconds = patch.end;
  if (patch.outfitKey !== undefined) row.outfit_key = patch.outfitKey;
  if (patch.notes !== undefined) row.notes = patch.notes.trim();
  if (row.name === "") throw new Error("A scene keeps a name.");
  const { error } = await table().update(row).eq("id", id);
  if (error) throw new Error(`could not save the scene: ${error.message}`);
}

export async function deleteScene(id: string): Promise<void> {
  const { error } = await table().delete().eq("id", id);
  if (error) throw new Error(`could not remove the scene: ${error.message}`);
}

export function useSceneMutations(projectId: string) {
  const qc = useQueryClient();
  const variationId = useActiveVariationId(projectId);
  const done = () => qc.invalidateQueries({ queryKey: scenesKeys.forVariation(projectId) });
  return {
    create: useMutation({
      mutationFn: (input: SceneWrite) => {
        if (!variationId) throw new Error("the project's video variation is not loaded yet");
        return createScene({ ...input, projectId, variationId });
      },
      onSuccess: done,
    }),
    createMany: useMutation({
      mutationFn: async (inputs: SceneWrite[]) => {
        if (!variationId) throw new Error("the project's video variation is not loaded yet");
        for (const input of inputs) await createScene({ ...input, projectId, variationId });
        return inputs.length;
      },
      onSuccess: done,
    }),
    update: useMutation({
      mutationFn: (input: { id: string; patch: Partial<SceneWrite> }) =>
        updateScene(input.id, input.patch),
      onSuccess: done,
    }),
    remove: useMutation({ mutationFn: (id: string) => deleteScene(id), onSuccess: done }),
  };
}
