/**
 * Treatment history — the effects. The database keeps a replaced treatment by itself (a trigger on the video
 * variation that holds it); the app reads the versions of the ACTIVE variation and, to restore one, makes a single
 * ordinary update to that variation, which the trigger records in turn. A revision is a change within a variation;
 * another video of the song is another variation (queries/variations.ts) with a history of its own.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import type { Json } from "@/integrations/supabase/aliases";
import { restoreWrite, versionFromRow, type TreatmentVersion, type TreatmentVersionRow } from "@/lib/treatment/versions";
import { projectsKeys } from "./projects";
import { useActiveVariationId } from "./storyboard";
import { writeDirection } from "./variations";

export const treatmentVersionsKeys = {
  forProject: (projectId: string, variationId?: string | null) => (variationId ? (["treatment_versions", projectId, variationId] as const) : (["treatment_versions", projectId] as const)),
};

const COLUMNS = "id, project_id, variation_id, created_at, replaced_by, treatment_text, treatment_mode, treatment_model, treatment_updated_at, notes, mood, visual_style";

export async function fetchTreatmentVersions(projectId: string, variationId: string): Promise<TreatmentVersion[]> {
  // the generated database types are regenerated by the host after a migration; until then the table is not in them
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).from("treatment_versions").select(COLUMNS).eq("project_id", projectId).eq("variation_id", variationId).order("created_at", { ascending: false }).limit(100);
  if (error) throw new Error(`could not read the treatment's versions: ${error.message}`);
  return ((data ?? []) as TreatmentVersionRow[]).map(versionFromRow);
}

/** The project's earlier treatments, newest first. */
export function useTreatmentVersions(projectId: string) {
  const variationId = useActiveVariationId(projectId);
  return useQuery({ queryKey: treatmentVersionsKeys.forProject(projectId, variationId ?? "_none_"), queryFn: () => fetchTreatmentVersions(projectId, variationId!), enabled: !!projectId && !!variationId });
}

/** Make an earlier version the current treatment. What was current is kept as a version by the database. */
export async function restoreTreatmentVersion(projectId: string, version: TreatmentVersion, currentTreatmentJson: unknown): Promise<void> {
  const write = restoreWrite(version, currentTreatmentJson, new Date().toISOString());
  // a version is restored into the variation it came from — never into whichever is active
  try {
    await writeDirection(projectId, { treatment_json: write.treatment_json as unknown as Json, notes: write.notes, mood: write.mood, visual_style: write.visual_style }, version.variationId);
  } catch (e) {
    throw new Error(`could not restore that version: ${e instanceof Error ? e.message : String(e)}`);
  }
}

export function useRestoreTreatmentVersion(projectId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (input: { version: TreatmentVersion; currentTreatmentJson: unknown }) => restoreTreatmentVersion(projectId, input.version, input.currentTreatmentJson),
    onSuccess: async () => {
      await Promise.all([
        qc.invalidateQueries({ queryKey: projectsKeys.detail(projectId) }),
        qc.invalidateQueries({ queryKey: treatmentVersionsKeys.forProject(projectId) }),
      ]);
    },
  });
}
