/**
 * Treatment history — the effects. The database keeps a replaced treatment by itself (a trigger on the project); the
 * app reads the versions and, to restore one, makes a single ordinary update, which the trigger records in turn.
 */
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { supabase } from "@/lib/supabase";
import type { Json } from "@/integrations/supabase/aliases";
import { restoreWrite, versionFromRow, type TreatmentVersion, type TreatmentVersionRow } from "@/lib/treatment/versions";
import { projectsKeys } from "./projects";

export const treatmentVersionsKeys = {
  forProject: (projectId: string) => ["treatment_versions", projectId] as const,
};

const COLUMNS = "id, project_id, created_at, replaced_by, treatment_text, treatment_mode, treatment_model, treatment_updated_at, notes, mood, visual_style";

export async function fetchTreatmentVersions(projectId: string): Promise<TreatmentVersion[]> {
  // the generated database types are regenerated by the host after a migration; until then the table is not in them
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (supabase as any).from("treatment_versions").select(COLUMNS).eq("project_id", projectId).order("created_at", { ascending: false }).limit(100);
  if (error) throw new Error(`could not read the treatment's versions: ${error.message}`);
  return ((data ?? []) as TreatmentVersionRow[]).map(versionFromRow);
}

/** The project's earlier treatments, newest first. */
export function useTreatmentVersions(projectId: string) {
  return useQuery({ queryKey: treatmentVersionsKeys.forProject(projectId), queryFn: () => fetchTreatmentVersions(projectId), enabled: !!projectId });
}

/** Make an earlier version the current treatment. What was current is kept as a version by the database. */
export async function restoreTreatmentVersion(projectId: string, version: TreatmentVersion, currentTreatmentJson: unknown): Promise<void> {
  const write = restoreWrite(version, currentTreatmentJson, new Date().toISOString());
  const { error } = await supabase
    .from("video_projects")
    .update({ treatment_json: write.treatment_json as unknown as Json, notes: write.notes, mood: write.mood, visual_style: write.visual_style })
    .eq("id", projectId);
  if (error) throw new Error(`could not restore that version: ${error.message}`);
}

export function useRestoreTreatmentVersion(projectId: string) {
  const qc = useQueryClient();
  return useMutation({
    mutationFn: (input: { version: TreatmentVersion; currentTreatmentJson: unknown }) => restoreTreatmentVersion(projectId, input.version, input.currentTreatmentJson),
    onSuccess: async () => {
      await Promise.all([
        qc.invalidateQueries({ queryKey: projectsKeys.detail(projectId) }),
        qc.invalidateQueries({ queryKey: treatmentVersionsKeys.forProject(projectId) }),
      ]);
    },
  });
}
