#!/usr/bin/env node
/**
 * Builds supabase/functions/avt-mcp/catalog.generated.ts: the tables avt-mcp knows, and for every edge function its
 * own header notes and request type, read from its source. An outside AI (ChatGPT, Grok) has no copy of this repo;
 * this is how it learns what each function takes — from the code, so the notes cannot drift from it.
 *
 *   node scripts/mcp/build-catalog.mjs          # write
 *   node scripts/mcp/build-catalog.mjs --check  # exit 1 when the file is out of date (the test runs this)
 */
import { existsSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const FUNCTIONS = join(ROOT, "supabase/functions");
const OUT = join(FUNCTIONS, "avt-mcp/catalog.generated.ts");
const TYPES = join(ROOT, "src/integrations/supabase/types.ts");
/** Tables added by migrations the generated types have not caught up with yet. */
const EXTRA_TABLES = [];
const HEADER_MAX = 3000;
const TYPE_MAX = 4000;

export function tablesFrom(typesSrc) {
  const start = typesSrc.indexOf("    Tables: {");
  const end = typesSrc.indexOf("    Views: {", start);
  if (start < 0 || end < 0) throw new Error("no Tables block in the generated types");
  const names = [...typesSrc.slice(start, end).matchAll(/^ {6}([a-z_][a-z0-9_]*): \{$/gm)].map((m) => m[1]);
  return [...new Set([...names, ...EXTRA_TABLES])].sort();
}

/** The comment block a function opens with: its own description of what it does and costs. */
export function headerOf(src) {
  const lines = src.split("\n");
  const out = [];
  let inBlock = false;
  for (const line of lines) {
    const t = line.trim();
    if (!inBlock && t.startsWith("/*")) inBlock = true;
    if (inBlock) {
      out.push(t.replace(/^\/\*\*?|\*\/$|^\*\s?/g, "").trimEnd());
      if (t.endsWith("*/")) inBlock = false;
      continue;
    }
    if (t.startsWith("//")) {
      out.push(t.replace(/^\/\/\s?/, ""));
      continue;
    }
    if (t === "" && out.length === 0) continue;
    break;
  }
  const text = out.join("\n").replace(/^[=\-\s]+$/gm, "").replace(/\n{3,}/g, "\n\n").trim();
  return text.length > HEADER_MAX ? `${text.slice(0, HEADER_MAX)}…` : text;
}

/** The request type(s) a function parses its body into: `type Body = {…}` / `interface …Request {…}` and kin. */
export function requestTypesOf(src) {
  const out = [];
  const re = /^(?:export\s+)?(?:type|interface)\s+(\w*(?:Body|Request|Req|Payload|Input)\w*)\b[^\n]*\{/gm;
  for (const m of src.matchAll(re)) {
    let depth = 0;
    let i = m.index + m[0].length - 1;
    for (; i < src.length; i++) {
      if (src[i] === "{") depth++;
      else if (src[i] === "}" && --depth === 0) break;
    }
    out.push(src.slice(m.index, i + 1));
  }
  const text = out.join("\n\n");
  return text.length > TYPE_MAX ? `${text.slice(0, TYPE_MAX)}\n…` : text;
}

export function build() {
  const tables = tablesFrom(readFileSync(TYPES, "utf8"));
  const functions = readdirSync(FUNCTIONS)
    .filter((d) => !d.startsWith("_") && statSync(join(FUNCTIONS, d)).isDirectory() && existsSync(join(FUNCTIONS, d, "index.ts")))
    .sort()
    .map((name) => {
      const index = readFileSync(join(FUNCTIONS, name, "index.ts"), "utf8");
      const contract = existsSync(join(FUNCTIONS, name, "contract.ts")) ? readFileSync(join(FUNCTIONS, name, "contract.ts"), "utf8") : "";
      return { name, notes: headerOf(index), request: requestTypesOf(`${index}\n${contract}`) };
    });
  return [
    "// GENERATED by scripts/mcp/build-catalog.mjs — do not edit. Re-run it after adding a table or a function.",
    `export const KNOWN_TABLES: readonly string[] = ${JSON.stringify(tables)};`,
    `export const FUNCTION_DOCS: readonly { name: string; notes: string; request: string }[] = ${JSON.stringify(functions, null, 1)};`,
    "",
  ].join("\n");
}

if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const next = build();
  if (process.argv.includes("--check")) {
    const now = existsSync(OUT) ? readFileSync(OUT, "utf8") : "";
    if (now !== next) {
      console.error("catalog.generated.ts is out of date — run: node scripts/mcp/build-catalog.mjs");
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, next);
    console.log(`wrote ${OUT}`);
  }
}
