/**
 * ShotPrevis — the previs surface treatment cards import (Lane E).
 *
 * Given a Shot Spec, renders a short animated preview of the shot's framing and
 * camera move. The sketch is deterministic and free (see {@link generatePrevis}):
 * there is no "generate" button and no loading state because there is no model
 * call — the preview simply reflects the current spec.
 *
 * If the spec already references a REAL rendered/approved previs asset (a clip
 * or frame in storage, not a synthesized `data:` URI) we show that instead of
 * the sketch, so this component never masks production work.
 *
 * Engineering mode ({@link useEngineeringMode}) reveals the derivation details
 * (seed / palette / motion transform) beneath the preview.
 */

import { useMemo } from "react";
import { Film } from "lucide-react";
import { AspectRatio } from "@/components/ui/aspect-ratio";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { useEngineeringMode } from "@/lib/ux/engineeringMode";
import type { ShotSpec } from "@/lib/treatment/shotSpec";
import { generatePrevis, hasRealPrevis } from "@/lib/previs";

const STATUS_VARIANT: Record<string, "default" | "secondary" | "outline"> = {
  approved: "default",
  rendered: "default",
  sketch: "secondary",
  none: "outline",
};

export type ShotPrevisProps = {
  spec: ShotSpec;
  className?: string;
  /** Hide the caption/detail footer, e.g. in a dense grid. Default false. */
  compact?: boolean;
};

export function ShotPrevis({ spec, className, compact = false }: ShotPrevisProps) {
  const { isEngineering } = useEngineeringMode();

  const real = hasRealPrevis(spec.previs);
  const generated = useMemo(() => (real ? null : generatePrevis(spec)), [spec, real]);

  const status = spec.previs.status === "none" && generated ? "sketch" : spec.previs.status;
  const statusVariant = STATUS_VARIANT[status] ?? "outline";

  return (
    <section className={cn("space-y-2", className)} data-testid="shot-previs">
      <div className="flex items-center justify-between">
        <h3 className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">
          <Film className="h-3 w-3" aria-hidden />
          Previs
        </h3>
        <Badge variant={statusVariant} className="capitalize">
          {status}
        </Badge>
      </div>

      <div className="overflow-hidden rounded-md border border-border bg-black/40">
        <AspectRatio ratio={16 / 9}>
          {real ? (
            // Real asset: image OR video (a poster/frame is always safe as <img>).
            <img
              src={spec.previs.uri ?? undefined}
              alt={`Previs for ${spec.title || spec.purpose}`}
              className="h-full w-full object-cover"
            />
          ) : (
            // Deterministic animated sketch — inlined so the SMIL animation runs.
            // The SVG is generated by our own renderer from validated spec data
            // (all text is escaped in renderSvg), so there is no untrusted HTML.
            <div
              className="h-full w-full [&>svg]:h-full [&>svg]:w-full"
              dangerouslySetInnerHTML={{ __html: generated!.svg }}
            />
          )}
        </AspectRatio>
      </div>

      {!compact && (
        <div className="space-y-1">
          {generated ? (
            <p className="text-[11px] text-muted-foreground">
              {generated.plan.captions.framing} · {generated.plan.captions.motion} ·{" "}
              {generated.plan.captions.duration}
              <span className="ml-1 opacity-60">· deterministic · no render cost</span>
            </p>
          ) : (
            <p className="text-[11px] text-muted-foreground">Real previs asset · {status}</p>
          )}

          {isEngineering && generated && (
            <dl className="grid grid-cols-2 gap-x-3 gap-y-0.5 font-mono text-[10px] text-muted-foreground/80">
              <div>
                <dt className="inline">seed </dt>
                <dd className="inline">{generated.plan.seed.toString(36)}</dd>
              </div>
              <div>
                <dt className="inline">lens </dt>
                <dd className="inline">{generated.plan.captions.lens}</dd>
              </div>
              <div>
                <dt className="inline">motion </dt>
                <dd className="inline">{generated.plan.motion.transform?.type ?? "static"}</dd>
              </div>
              <div>
                <dt className="inline">uri </dt>
                <dd className="inline">{generated.dataUri.length}b svg</dd>
              </div>
            </dl>
          )}
        </div>
      )}
    </section>
  );
}
