import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { hasDirectedChange } from "@/lib/storyboard/boxes";
import { useQueryClient } from "@tanstack/react-query";
import { PageHeader } from "@/components/AppShell";
import { BatchRunView, type BatchRowView } from "@/components/runs/BatchRunView";
import { useProject } from "@/lib/queries/projects";
import { useLyricLines } from "@/lib/queries/lyricLines";
import { useStoryboardBoxes } from "@/lib/queries/storyboard";
import { providerJobsKeys, useProjectProviderJobs } from "@/lib/providerJobs/queries";
import { useJobProgress, type ProgressRow } from "@/lib/providerJobs/progress";
import { signedUrl } from "@/lib/storage";
import { aspectOfProject, stillRequestAspect } from "@/lib/project/aspect";
import { LOOK_PRESETS, compileToWorldBatch, phrasesFromShotSpecs, resolveLookPreset } from "@/lib/shotCompiler";
import {
  PROVIDER_REFUSALS,
  batchJobsByRun,
  estimateShotUsd,
  parseShotsJson,
  planRun,
  resultUrlOf,
  runPlan,
  settingsOf,
  shotState,
  spentEstimateUsd,
  type BatchJobRow,
  type BatchShot,
} from "@/lib/worldBatch";
import {
  browserRunnerDeps,
  clipSeconds,
  markJobFailed,
  uploadSourceClip,
  uploadStill,
} from "@/lib/worldBatch/browserDeps";

/**
 * Runs — the batch runner in the app. The same shot list the scripts run (shots.json) is submitted, polled and saved
 * from the owner's signed-in browser, so a paid round needs no login copied to any machine.
 */
type Patch = { source_path?: string; source_seconds?: number; still_path?: string };
type Saved = {
  shotsText: string;
  runId: string;
  ceilingUsd: number;
  lookPresetId: string;
  patches: Record<string, Patch>;
  unselected: string[];
};


function defaultRunId(now = new Date()): string {
  const p = (n: number) => String(n).padStart(2, "0");
  return `run-${now.getFullYear()}${p(now.getMonth() + 1)}${p(now.getDate())}-${p(now.getHours())}${p(now.getMinutes())}`;
}

function loadSaved(key: string): Partial<Saved> {
  try {
    return JSON.parse(localStorage.getItem(key) ?? "{}") as Partial<Saved>;
  } catch {
    return {};
  }
}

export default function BatchRunsPage({ projectId }: { projectId: string }) {
  const storeKey = `avt.batchRuns.${projectId}`;
  const initial = useMemo(() => loadSaved(storeKey), [storeKey]);
  const [shotsText, setShotsText] = useState(initial.shotsText ?? "");
  const [loadedText, setLoadedText] = useState(initial.shotsText ?? "");
  const [runId, setRunId] = useState(initial.runId ?? defaultRunId());
  const [ceilingUsd, setCeilingUsd] = useState(initial.ceilingUsd ?? 25);
  const [lookPresetId, setLookPresetId] = useState(initial.lookPresetId ?? "film_bar_v1");
  const [patches, setPatches] = useState<Record<string, Patch>>(initial.patches ?? {});
  const [unselected, setUnselected] = useState<string[]>(initial.unselected ?? []);
  const [running, setRunning] = useState(false);
  const [busy, setBusy] = useState<Record<string, string>>({});
  const [notes, setNotes] = useState<Record<string, string>>({});
  const [log, setLog] = useState<string[]>([]);
  const [stillLinks, setStillLinks] = useState<Record<string, string>>({});

  const qc = useQueryClient();
  const jobsQuery = useProjectProviderJobs(projectId);
  const projectQuery = useProject(projectId);
  const lyricLinesQuery = useLyricLines(projectId);
  const boxesQuery = useStoryboardBoxes(projectId);

  useEffect(() => {
    try {
      const saved: Saved = { shotsText: loadedText, runId, ceilingUsd, lookPresetId, patches, unselected };
      localStorage.setItem(storeKey, JSON.stringify(saved));
    } catch {
      // storage is a convenience here; the jobs table is the record
    }
  }, [storeKey, loadedText, runId, ceilingUsd, lookPresetId, patches, unselected]);

  const say = useCallback((line: string) => {
    const t = new Date().toISOString().slice(11, 19);
    setLog((l) => [...l.slice(-199), `${t} ${line}`]);
  }, []);

  const parsed = useMemo(
    () => (loadedText.trim() ? parseShotsJson(loadedText) : { shots: [] as BatchShot[], errors: [] as string[] }),
    [loadedText],
  );
  const shots = useMemo(
    () => parsed.shots.map((s) => ({ ...s, ...(patches[s.id] ?? {}) }) as BatchShot),
    [parsed.shots, patches],
  );
  const runJobs = useMemo(
    () => batchJobsByRun((jobsQuery.data ?? []) as unknown as BatchJobRow[]).get(runId) ?? [],
    [jobsQuery.data, runId],
  );
  const selectedShots = useMemo(() => shots.filter((s) => !unselected.includes(s.id)), [shots, unselected]);
  const plan = useMemo(() => planRun(selectedShots, runJobs), [selectedShots, runJobs]);

  // The stills each shot has (given, or generated by a submit — also a failed one): picked first, then candidates.
  const stillPathsByShot = useMemo(() => {
    const out: Record<string, string[]> = {};
    for (const shot of shots) {
      const mine = runJobs.map(settingsOf).filter((x) => x?.batchShotId === shot.id);
      const picked = shot.still_path ?? mine.map((x) => x?.stillPath).find((p) => !!p) ?? null;
      const candidates = mine.flatMap((x) => x?.stillCandidates ?? []);
      out[shot.id] = [...new Set([picked, ...candidates].filter((p): p is string => !!p))];
    }
    return out;
  }, [shots, runJobs]);
  const stillKey = Object.values(stillPathsByShot).flat().join("|");
  useEffect(() => {
    const missing = [...new Set(Object.values(stillPathsByShot).flat())].filter((p) => !stillLinks[p]);
    if (missing.length === 0) return;
    let stop = false;
    void Promise.all(missing.map((p) => signedUrl("project-references", p, 3600).then((u) => [p, u] as const).catch(() => null))).then((pairs) => {
      if (stop) return;
      setStillLinks((m) => ({ ...m, ...Object.fromEntries(pairs.filter((x): x is readonly [string, string] => !!x)) }));
    });
    return () => {
      stop = true;
    };
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [stillKey]);

  const rows: BatchRowView[] = useMemo(
    () =>
      shots.map((shot) => {
        const state = shotState(shot, runJobs);
        const job = "job" in state ? state.job : null;
        return {
          shot,
          state,
          estimateUsd: estimateShotUsd(shot),
          selected: !unselected.includes(shot.id),
          resultUrl: job ? resultUrlOf(job) : null,
          storedPath: job?.result_asset_id ? `asset ${job.result_asset_id}` : null,
          stillUrls: (stillPathsByShot[shot.id] ?? []).map((p) => stillLinks[p]).filter((u): u is string => !!u),
          note: notes[shot.id] ?? null,
          busy: busy[shot.id] ?? null,
        };
      }),
    [shots, runJobs, unselected, notes, busy, stillPathsByShot, stillLinks],
  );

  const refetchJobs = useCallback(
    () => qc.invalidateQueries({ queryKey: providerJobsKeys.forProject(projectId) }),
    [qc, projectId],
  );

  // The server moves the jobs (provider-jobs-tick): it asks the provider, saves each finished clip and — for a job
  // made for a storyboard shot — puts it on the shot. This page asks for a tick while a job is unfinished and reads
  // the rows; it polls nothing and saves nothing itself, so closing it stops nothing.
  const seen = useRef<Map<string, string>>(new Map());
  useJobProgress(runJobs as unknown as ProgressRow[], async (reply) => {
    for (const r of reply?.reports ?? []) {
      const job = runJobs.find((j) => j.id === r.jobId);
      const shotId = String(settingsOf(job as BatchJobRow)?.batchShotId ?? r.jobId);
      const line = `${shotId}: ${r.did.join(" → ") || r.state}${r.note ? ` (${r.note})` : ""}`;
      // say each thing once: a job that is still rendering reports the same line every tick
      if (seen.current.get(r.jobId) === line) continue;
      seen.current.set(r.jobId, line);
      if (r.state === "retry" && r.note) setNotes((n) => ({ ...n, [shotId]: `not finished yet: ${r.note}` }));
      say(line);
    }
    await refetchJobs();
  });

  const load = useCallback(
    (text: string) => {
      setShotsText(text);
      setLoadedText(text);
      setUnselected([]);
      const r = parseShotsJson(text);
      say(`loaded ${r.shots.length} shot(s)${r.errors.length ? `, ${r.errors.length} rejected` : ""}`);
    },
    [say],
  );

  const attach = useCallback(
    async (shotId: string, file: File, kind: "source" | "still") => {
      setBusy((b) => ({ ...b, [shotId]: kind === "source" ? "uploading the source clip…" : "uploading the still…" }));
      try {
        if (kind === "source") {
          const [path, seconds] = await Promise.all([uploadSourceClip(projectId, runId, shotId, file), clipSeconds(file)]);
          setPatches((p) => ({ ...p, [shotId]: { ...p[shotId], source_path: path, ...(seconds ? { source_seconds: seconds } : {}) } }));
          say(`${shotId} source clip stored (${seconds ? `${seconds} s` : "duration unread"})`);
        } else {
          const path = await uploadStill(projectId, runId, shotId, file);
          setPatches((p) => ({ ...p, [shotId]: { ...p[shotId], still_path: path } }));
          say(`${shotId} still stored`);
        }
      } catch (e) {
        say(`${shotId} upload failed: ${e instanceof Error ? e.message : String(e)}`);
      } finally {
        setBusy((b) => {
          const { [shotId]: _gone, ...rest } = b;
          return rest;
        });
      }
    },
    [projectId, runId, say],
  );

  const run = useCallback(async () => {
    setRunning(true);
    try {
      const { id: presetId, look } = resolveLookPreset(lookPresetId);
      const deps = await browserRunnerDeps();
      // a shot compiled from the storyboard is filed under its box's record, so its clip lands on that box
      const shotIds = Object.fromEntries((boxesQuery.data ?? []).map((b) => [b.key, b.id]));
      say(`submitting ${plan.submit.length} shot(s), estimate $${plan.estimateUsd.toFixed(2)}`);
      const out = await runPlan(
        plan,
        { projectId, runId, lookPresetId: presetId, look, shotIds },
        deps,
        {
          ceilingUsd,
          refusalPatterns: PROVIDER_REFUSALS,
          onProgress: (shotId, phase) => {
            setBusy((b) => {
              if (phase === "submitting") return { ...b, [shotId]: "submitting…" };
              const { [shotId]: _gone, ...rest } = b;
              return rest;
            });
            if (phase !== "submitting") void refetchJobs();
          },
        },
      );
      for (const s of out.submitted) say(`submitted → ${s.providerJobId}`);
      for (const f of out.failed) say(`FAILED ${f.error}`);
      for (const s of out.skipped) say(`skipped ${s.shot.id}: ${s.why}`);
    } catch (e) {
      say(e instanceof Error ? e.message : String(e));
    } finally {
      setRunning(false);
      void refetchJobs();
    }
  }, [plan, projectId, runId, lookPresetId, ceilingUsd, refetchJobs, say, boxesQuery.data]);

  // The storyboard IS the shot list: the boxes are read from their own records (generated + the director's edits,
  // already resolved), never from the treatment's stored clips.
  const boxes = boxesQuery.data ?? [];
  const fromStoryboard = useCallback(() => {
    if (boxes.length === 0) {
      say("this project has no storyboard shots to compile");
      return;
    }
    // A shot that changes while it plays is never compiled into one static request (storyboard/temporal.ts): it is
    // left out here, by name. Its clip is made on the storyboard, where its beats are split, made effects, or asked
    // for in order.
    const changing = boxes.filter((b) => hasDirectedChange(b.spec));
    const single = boxes.filter((b) => !hasDirectedChange(b.spec));
    if (changing.length > 0) {
      say(`left out ${changing.length} shot(s) that change while they play — ${changing.map((b) => b.key).join(", ")}: generate those from the storyboard, where their timed beats are handled`);
    }
    if (single.length === 0) return;
    const phrases = phrasesFromShotSpecs(single.map((b) => b.spec), lyricLinesQuery.data ?? []);
    // asked for in the project's frame (or the nearest shape the image model has)
    const compiled = compileToWorldBatch({ phrases, lookPresetId, aspectDefault: stillRequestAspect(aspectOfProject(projectQuery.data)).aspect }).shots;
    const text = JSON.stringify(compiled, null, 1);
    setShotsText(text);
    setLoadedText(text);
    // a whole storyboard is many paid shots: nothing is ticked until the director ticks it
    setUnselected(compiled.map((s) => s.id));
    say(`compiled ${compiled.length} world shot(s) from the storyboard — tick the ones to run`);
  }, [boxes, lyricLinesQuery.data, lookPresetId, say, projectQuery.data]);

  return (
    <>
      <PageHeader title="Runs" subtitle="Submit a shot list to the providers from here; every job is recorded before it is sent" variant="compact" />
      <div className="px-4 py-6 md:px-8">
        <BatchRunView
          runId={runId}
          onRunId={(v) => setRunId(v.replace(/[^A-Za-z0-9_.-]/g, "_").slice(0, 60))}
          lookPresetId={lookPresetId}
          lookPresetIds={Object.keys(LOOK_PRESETS)}
          onLookPreset={setLookPresetId}
          ceilingUsd={ceilingUsd}
          onCeiling={setCeilingUsd}
          shotsText={shotsText}
          onShotsText={setShotsText}
          onLoad={() => load(shotsText)}
          onLoadFile={(f) => void f.text().then(load)}
          onFromStoryboard={boxes.length > 0 ? fromStoryboard : undefined}
          parseErrors={parsed.errors}
          rows={rows}
          plan={plan}
          running={running}
          log={log}
          spentUsd={spentEstimateUsd(runJobs)}
          onToggle={(id) => setUnselected((u) => (u.includes(id) ? u.filter((x) => x !== id) : [...u, id]))}
          onAttachSource={(id, f) => void attach(id, f, "source")}
          onAttachStill={(id, f) => void attach(id, f, "still")}
          onMarkFailed={(id) => {
            const st = rows.find((r) => r.shot.id === id)?.state;
            if (st?.state !== "unreconciled") return;
            void markJobFailed(st.job.id, "marked failed by the operator after checking the provider")
              .then(refetchJobs)
              .catch((e) => say(e instanceof Error ? e.message : String(e)));
          }}
          onRun={() => void run()}
        />
      </div>
    </>
  );
}
