/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LooksRouteImport } from './routes/looks'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as LooksIndexRouteImport } from './routes/looks.index'
import { Route as ArtistsIndexRouteImport } from './routes/artists.index'
import { Route as ProjectsNewRouteImport } from './routes/projects.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as LibraryPropsRouteImport } from './routes/library.props'
import { Route as LibraryLocationsRouteImport } from './routes/library.locations'
import { Route as ArtistsNewRouteImport } from './routes/artists.new'
import { Route as ArtistsIdRouteImport } from './routes/artists.$id'
import { Route as ProjectsIdIndexRouteImport } from './routes/projects.$id.index'
import { Route as ArtistsIdIndexRouteImport } from './routes/artists.$id.index'
import { Route as ProjectsIdTreatmentRouteImport } from './routes/projects.$id.treatment'
import { Route as ProjectsIdShotsRouteImport } from './routes/projects.$id.shots'
import { Route as ProjectsIdReviewRouteImport } from './routes/projects.$id.review'
import { Route as ProjectsIdPromptRouteImport } from './routes/projects.$id.prompt'
import { Route as ProjectsIdExportRouteImport } from './routes/projects.$id.export'
import { Route as ProjectsIdContinuityRouteImport } from './routes/projects.$id.continuity'
import { Route as ProjectsIdAssetsRouteImport } from './routes/projects.$id.assets'
import { Route as ArtistsIdLooksRouteImport } from './routes/artists.$id.looks'
import { Route as ArtistsIdLooksIndexRouteImport } from './routes/artists.$id.looks.index'
import { Route as ProjectsIdShotsShotIdRouteImport } from './routes/projects.$id.shots.$shotId'
import { Route as ArtistsIdLooksNewRouteImport } from './routes/artists.$id.looks.new'
import { Route as ArtistsIdLooksLookIdRouteImport } from './routes/artists.$id.looks.$lookId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LooksRoute = LooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const LooksIndexRoute = LooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LooksRoute,
} as any)
const ArtistsIndexRoute = ArtistsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsRoute,
} as any)
const ProjectsNewRoute = ProjectsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const LibraryPropsRoute = LibraryPropsRouteImport.update({
  id: '/library/props',
  path: '/library/props',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryLocationsRoute = LibraryLocationsRouteImport.update({
  id: '/library/locations',
  path: '/library/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsNewRoute = ArtistsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ArtistsRoute,
} as any)
const ArtistsIdRoute = ArtistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ArtistsRoute,
} as any)
const ProjectsIdIndexRoute = ProjectsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ArtistsIdIndexRoute = ArtistsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsIdRoute,
} as any)
const ProjectsIdTreatmentRoute = ProjectsIdTreatmentRouteImport.update({
  id: '/treatment',
  path: '/treatment',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdShotsRoute = ProjectsIdShotsRouteImport.update({
  id: '/shots',
  path: '/shots',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdReviewRoute = ProjectsIdReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdPromptRoute = ProjectsIdPromptRouteImport.update({
  id: '/prompt',
  path: '/prompt',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdExportRoute = ProjectsIdExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdContinuityRoute = ProjectsIdContinuityRouteImport.update({
  id: '/continuity',
  path: '/continuity',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ProjectsIdAssetsRoute = ProjectsIdAssetsRouteImport.update({
  id: '/assets',
  path: '/assets',
  getParentRoute: () => ProjectsIdRoute,
} as any)
const ArtistsIdLooksRoute = ArtistsIdLooksRouteImport.update({
  id: '/looks',
  path: '/looks',
  getParentRoute: () => ArtistsIdRoute,
} as any)
const ArtistsIdLooksIndexRoute = ArtistsIdLooksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArtistsIdLooksRoute,
} as any)
const ProjectsIdShotsShotIdRoute = ProjectsIdShotsShotIdRouteImport.update({
  id: '/$shotId',
  path: '/$shotId',
  getParentRoute: () => ProjectsIdShotsRoute,
} as any)
const ArtistsIdLooksNewRoute = ArtistsIdLooksNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ArtistsIdLooksRoute,
} as any)
const ArtistsIdLooksLookIdRoute = ArtistsIdLooksLookIdRouteImport.update({
  id: '/$lookId',
  path: '/$lookId',
  getParentRoute: () => ArtistsIdLooksRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/looks': typeof LooksRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/artists/$id': typeof ArtistsIdRouteWithChildren
  '/artists/new': typeof ArtistsNewRoute
  '/library/locations': typeof LibraryLocationsRoute
  '/library/props': typeof LibraryPropsRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/artists/': typeof ArtistsIndexRoute
  '/looks/': typeof LooksIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/artists/$id/looks': typeof ArtistsIdLooksRouteWithChildren
  '/projects/$id/assets': typeof ProjectsIdAssetsRoute
  '/projects/$id/continuity': typeof ProjectsIdContinuityRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/prompt': typeof ProjectsIdPromptRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/shots': typeof ProjectsIdShotsRouteWithChildren
  '/projects/$id/treatment': typeof ProjectsIdTreatmentRoute
  '/artists/$id/': typeof ArtistsIdIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/artists/$id/looks/$lookId': typeof ArtistsIdLooksLookIdRoute
  '/artists/$id/looks/new': typeof ArtistsIdLooksNewRoute
  '/projects/$id/shots/$shotId': typeof ProjectsIdShotsShotIdRoute
  '/artists/$id/looks/': typeof ArtistsIdLooksIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/settings': typeof SettingsRoute
  '/artists/new': typeof ArtistsNewRoute
  '/library/locations': typeof LibraryLocationsRoute
  '/library/props': typeof LibraryPropsRoute
  '/projects/new': typeof ProjectsNewRoute
  '/artists': typeof ArtistsIndexRoute
  '/looks': typeof LooksIndexRoute
  '/projects': typeof ProjectsIndexRoute
  '/projects/$id/assets': typeof ProjectsIdAssetsRoute
  '/projects/$id/continuity': typeof ProjectsIdContinuityRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/prompt': typeof ProjectsIdPromptRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/shots': typeof ProjectsIdShotsRouteWithChildren
  '/projects/$id/treatment': typeof ProjectsIdTreatmentRoute
  '/artists/$id': typeof ArtistsIdIndexRoute
  '/projects/$id': typeof ProjectsIdIndexRoute
  '/artists/$id/looks/$lookId': typeof ArtistsIdLooksLookIdRoute
  '/artists/$id/looks/new': typeof ArtistsIdLooksNewRoute
  '/projects/$id/shots/$shotId': typeof ProjectsIdShotsShotIdRoute
  '/artists/$id/looks': typeof ArtistsIdLooksIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artists': typeof ArtistsRouteWithChildren
  '/looks': typeof LooksRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/artists/$id': typeof ArtistsIdRouteWithChildren
  '/artists/new': typeof ArtistsNewRoute
  '/library/locations': typeof LibraryLocationsRoute
  '/library/props': typeof LibraryPropsRoute
  '/projects/$id': typeof ProjectsIdRouteWithChildren
  '/projects/new': typeof ProjectsNewRoute
  '/artists/': typeof ArtistsIndexRoute
  '/looks/': typeof LooksIndexRoute
  '/projects/': typeof ProjectsIndexRoute
  '/artists/$id/looks': typeof ArtistsIdLooksRouteWithChildren
  '/projects/$id/assets': typeof ProjectsIdAssetsRoute
  '/projects/$id/continuity': typeof ProjectsIdContinuityRoute
  '/projects/$id/export': typeof ProjectsIdExportRoute
  '/projects/$id/prompt': typeof ProjectsIdPromptRoute
  '/projects/$id/review': typeof ProjectsIdReviewRoute
  '/projects/$id/shots': typeof ProjectsIdShotsRouteWithChildren
  '/projects/$id/treatment': typeof ProjectsIdTreatmentRoute
  '/artists/$id/': typeof ArtistsIdIndexRoute
  '/projects/$id/': typeof ProjectsIdIndexRoute
  '/artists/$id/looks/$lookId': typeof ArtistsIdLooksLookIdRoute
  '/artists/$id/looks/new': typeof ArtistsIdLooksNewRoute
  '/projects/$id/shots/$shotId': typeof ProjectsIdShotsShotIdRoute
  '/artists/$id/looks/': typeof ArtistsIdLooksIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artists'
    | '/looks'
    | '/projects'
    | '/settings'
    | '/artists/$id'
    | '/artists/new'
    | '/library/locations'
    | '/library/props'
    | '/projects/$id'
    | '/projects/new'
    | '/artists/'
    | '/looks/'
    | '/projects/'
    | '/artists/$id/looks'
    | '/projects/$id/assets'
    | '/projects/$id/continuity'
    | '/projects/$id/export'
    | '/projects/$id/prompt'
    | '/projects/$id/review'
    | '/projects/$id/shots'
    | '/projects/$id/treatment'
    | '/artists/$id/'
    | '/projects/$id/'
    | '/artists/$id/looks/$lookId'
    | '/artists/$id/looks/new'
    | '/projects/$id/shots/$shotId'
    | '/artists/$id/looks/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/settings'
    | '/artists/new'
    | '/library/locations'
    | '/library/props'
    | '/projects/new'
    | '/artists'
    | '/looks'
    | '/projects'
    | '/projects/$id/assets'
    | '/projects/$id/continuity'
    | '/projects/$id/export'
    | '/projects/$id/prompt'
    | '/projects/$id/review'
    | '/projects/$id/shots'
    | '/projects/$id/treatment'
    | '/artists/$id'
    | '/projects/$id'
    | '/artists/$id/looks/$lookId'
    | '/artists/$id/looks/new'
    | '/projects/$id/shots/$shotId'
    | '/artists/$id/looks'
  id:
    | '__root__'
    | '/'
    | '/artists'
    | '/looks'
    | '/projects'
    | '/settings'
    | '/artists/$id'
    | '/artists/new'
    | '/library/locations'
    | '/library/props'
    | '/projects/$id'
    | '/projects/new'
    | '/artists/'
    | '/looks/'
    | '/projects/'
    | '/artists/$id/looks'
    | '/projects/$id/assets'
    | '/projects/$id/continuity'
    | '/projects/$id/export'
    | '/projects/$id/prompt'
    | '/projects/$id/review'
    | '/projects/$id/shots'
    | '/projects/$id/treatment'
    | '/artists/$id/'
    | '/projects/$id/'
    | '/artists/$id/looks/$lookId'
    | '/artists/$id/looks/new'
    | '/projects/$id/shots/$shotId'
    | '/artists/$id/looks/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtistsRoute: typeof ArtistsRouteWithChildren
  LooksRoute: typeof LooksRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  LibraryLocationsRoute: typeof LibraryLocationsRoute
  LibraryPropsRoute: typeof LibraryPropsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/looks': {
      id: '/looks'
      path: '/looks'
      fullPath: '/looks'
      preLoaderRoute: typeof LooksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/looks/': {
      id: '/looks/'
      path: '/'
      fullPath: '/looks/'
      preLoaderRoute: typeof LooksIndexRouteImport
      parentRoute: typeof LooksRoute
    }
    '/artists/': {
      id: '/artists/'
      path: '/'
      fullPath: '/artists/'
      preLoaderRoute: typeof ArtistsIndexRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/projects/new': {
      id: '/projects/new'
      path: '/new'
      fullPath: '/projects/new'
      preLoaderRoute: typeof ProjectsNewRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/library/props': {
      id: '/library/props'
      path: '/library/props'
      fullPath: '/library/props'
      preLoaderRoute: typeof LibraryPropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/locations': {
      id: '/library/locations'
      path: '/library/locations'
      fullPath: '/library/locations'
      preLoaderRoute: typeof LibraryLocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists/new': {
      id: '/artists/new'
      path: '/new'
      fullPath: '/artists/new'
      preLoaderRoute: typeof ArtistsNewRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/artists/$id': {
      id: '/artists/$id'
      path: '/$id'
      fullPath: '/artists/$id'
      preLoaderRoute: typeof ArtistsIdRouteImport
      parentRoute: typeof ArtistsRoute
    }
    '/projects/$id/': {
      id: '/projects/$id/'
      path: '/'
      fullPath: '/projects/$id/'
      preLoaderRoute: typeof ProjectsIdIndexRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/artists/$id/': {
      id: '/artists/$id/'
      path: '/'
      fullPath: '/artists/$id/'
      preLoaderRoute: typeof ArtistsIdIndexRouteImport
      parentRoute: typeof ArtistsIdRoute
    }
    '/projects/$id/treatment': {
      id: '/projects/$id/treatment'
      path: '/treatment'
      fullPath: '/projects/$id/treatment'
      preLoaderRoute: typeof ProjectsIdTreatmentRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/shots': {
      id: '/projects/$id/shots'
      path: '/shots'
      fullPath: '/projects/$id/shots'
      preLoaderRoute: typeof ProjectsIdShotsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/review': {
      id: '/projects/$id/review'
      path: '/review'
      fullPath: '/projects/$id/review'
      preLoaderRoute: typeof ProjectsIdReviewRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/prompt': {
      id: '/projects/$id/prompt'
      path: '/prompt'
      fullPath: '/projects/$id/prompt'
      preLoaderRoute: typeof ProjectsIdPromptRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/export': {
      id: '/projects/$id/export'
      path: '/export'
      fullPath: '/projects/$id/export'
      preLoaderRoute: typeof ProjectsIdExportRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/continuity': {
      id: '/projects/$id/continuity'
      path: '/continuity'
      fullPath: '/projects/$id/continuity'
      preLoaderRoute: typeof ProjectsIdContinuityRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/projects/$id/assets': {
      id: '/projects/$id/assets'
      path: '/assets'
      fullPath: '/projects/$id/assets'
      preLoaderRoute: typeof ProjectsIdAssetsRouteImport
      parentRoute: typeof ProjectsIdRoute
    }
    '/artists/$id/looks': {
      id: '/artists/$id/looks'
      path: '/looks'
      fullPath: '/artists/$id/looks'
      preLoaderRoute: typeof ArtistsIdLooksRouteImport
      parentRoute: typeof ArtistsIdRoute
    }
    '/artists/$id/looks/': {
      id: '/artists/$id/looks/'
      path: '/'
      fullPath: '/artists/$id/looks/'
      preLoaderRoute: typeof ArtistsIdLooksIndexRouteImport
      parentRoute: typeof ArtistsIdLooksRoute
    }
    '/projects/$id/shots/$shotId': {
      id: '/projects/$id/shots/$shotId'
      path: '/$shotId'
      fullPath: '/projects/$id/shots/$shotId'
      preLoaderRoute: typeof ProjectsIdShotsShotIdRouteImport
      parentRoute: typeof ProjectsIdShotsRoute
    }
    '/artists/$id/looks/new': {
      id: '/artists/$id/looks/new'
      path: '/new'
      fullPath: '/artists/$id/looks/new'
      preLoaderRoute: typeof ArtistsIdLooksNewRouteImport
      parentRoute: typeof ArtistsIdLooksRoute
    }
    '/artists/$id/looks/$lookId': {
      id: '/artists/$id/looks/$lookId'
      path: '/$lookId'
      fullPath: '/artists/$id/looks/$lookId'
      preLoaderRoute: typeof ArtistsIdLooksLookIdRouteImport
      parentRoute: typeof ArtistsIdLooksRoute
    }
  }
}

interface ArtistsIdLooksRouteChildren {
  ArtistsIdLooksLookIdRoute: typeof ArtistsIdLooksLookIdRoute
  ArtistsIdLooksNewRoute: typeof ArtistsIdLooksNewRoute
  ArtistsIdLooksIndexRoute: typeof ArtistsIdLooksIndexRoute
}

const ArtistsIdLooksRouteChildren: ArtistsIdLooksRouteChildren = {
  ArtistsIdLooksLookIdRoute: ArtistsIdLooksLookIdRoute,
  ArtistsIdLooksNewRoute: ArtistsIdLooksNewRoute,
  ArtistsIdLooksIndexRoute: ArtistsIdLooksIndexRoute,
}

const ArtistsIdLooksRouteWithChildren = ArtistsIdLooksRoute._addFileChildren(
  ArtistsIdLooksRouteChildren,
)

interface ArtistsIdRouteChildren {
  ArtistsIdLooksRoute: typeof ArtistsIdLooksRouteWithChildren
  ArtistsIdIndexRoute: typeof ArtistsIdIndexRoute
}

const ArtistsIdRouteChildren: ArtistsIdRouteChildren = {
  ArtistsIdLooksRoute: ArtistsIdLooksRouteWithChildren,
  ArtistsIdIndexRoute: ArtistsIdIndexRoute,
}

const ArtistsIdRouteWithChildren = ArtistsIdRoute._addFileChildren(
  ArtistsIdRouteChildren,
)

interface ArtistsRouteChildren {
  ArtistsIdRoute: typeof ArtistsIdRouteWithChildren
  ArtistsNewRoute: typeof ArtistsNewRoute
  ArtistsIndexRoute: typeof ArtistsIndexRoute
}

const ArtistsRouteChildren: ArtistsRouteChildren = {
  ArtistsIdRoute: ArtistsIdRouteWithChildren,
  ArtistsNewRoute: ArtistsNewRoute,
  ArtistsIndexRoute: ArtistsIndexRoute,
}

const ArtistsRouteWithChildren =
  ArtistsRoute._addFileChildren(ArtistsRouteChildren)

interface LooksRouteChildren {
  LooksIndexRoute: typeof LooksIndexRoute
}

const LooksRouteChildren: LooksRouteChildren = {
  LooksIndexRoute: LooksIndexRoute,
}

const LooksRouteWithChildren = LooksRoute._addFileChildren(LooksRouteChildren)

interface ProjectsIdShotsRouteChildren {
  ProjectsIdShotsShotIdRoute: typeof ProjectsIdShotsShotIdRoute
}

const ProjectsIdShotsRouteChildren: ProjectsIdShotsRouteChildren = {
  ProjectsIdShotsShotIdRoute: ProjectsIdShotsShotIdRoute,
}

const ProjectsIdShotsRouteWithChildren = ProjectsIdShotsRoute._addFileChildren(
  ProjectsIdShotsRouteChildren,
)

interface ProjectsIdRouteChildren {
  ProjectsIdAssetsRoute: typeof ProjectsIdAssetsRoute
  ProjectsIdContinuityRoute: typeof ProjectsIdContinuityRoute
  ProjectsIdExportRoute: typeof ProjectsIdExportRoute
  ProjectsIdPromptRoute: typeof ProjectsIdPromptRoute
  ProjectsIdReviewRoute: typeof ProjectsIdReviewRoute
  ProjectsIdShotsRoute: typeof ProjectsIdShotsRouteWithChildren
  ProjectsIdTreatmentRoute: typeof ProjectsIdTreatmentRoute
  ProjectsIdIndexRoute: typeof ProjectsIdIndexRoute
}

const ProjectsIdRouteChildren: ProjectsIdRouteChildren = {
  ProjectsIdAssetsRoute: ProjectsIdAssetsRoute,
  ProjectsIdContinuityRoute: ProjectsIdContinuityRoute,
  ProjectsIdExportRoute: ProjectsIdExportRoute,
  ProjectsIdPromptRoute: ProjectsIdPromptRoute,
  ProjectsIdReviewRoute: ProjectsIdReviewRoute,
  ProjectsIdShotsRoute: ProjectsIdShotsRouteWithChildren,
  ProjectsIdTreatmentRoute: ProjectsIdTreatmentRoute,
  ProjectsIdIndexRoute: ProjectsIdIndexRoute,
}

const ProjectsIdRouteWithChildren = ProjectsIdRoute._addFileChildren(
  ProjectsIdRouteChildren,
)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRouteWithChildren
  ProjectsNewRoute: typeof ProjectsNewRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRouteWithChildren,
  ProjectsNewRoute: ProjectsNewRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtistsRoute: ArtistsRouteWithChildren,
  LooksRoute: LooksRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  LibraryLocationsRoute: LibraryLocationsRoute,
  LibraryPropsRoute: LibraryPropsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
