/**
 * Stable type-alias shim over the auto-generated Supabase `Database` type.
 *
 * `src/integrations/supabase/types.ts` is regenerated by Lovable Cloud and
 * only exports `Database` / `Json` / the `Tables<>` / `Enums<>` helpers.
 * App code historically imports named row aliases (Artist, Shot, …) and
 * enum aliases (ShotStatus, ProviderName, …) from that file. To keep the
 * codebase stable across regenerations, derive every alias here and import
 * from `@/integrations/supabase/aliases` instead.
 */
import type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json } from "./types";

export type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json };

// ---------- Row aliases (Tables<...>) ----------
export type Artist = Tables<"artists">;
export type ArtistAsset = Tables<"artist_assets">;
export type CharacterFeature = Tables<"character_features">;
export type ClipReview = Tables<"clip_reviews">;
export type ExportPackage = Tables<"export_packages">;
export type GenerationFeasibility = Tables<"generation_feasibility">;
export type LocationLibrary = Tables<"location_library">;
export type ProjectAsset = Tables<"project_assets">;
export type ProjectLocationPick = Tables<"project_location_picks">;
export type ProjectPropPick = Tables<"project_prop_picks">;
export type Prompt = Tables<"prompts">;
export type PromptTemplate = Tables<"prompt_templates">;
export type PropLibrary = Tables<"prop_library">;
export type Product = Tables<"products">;
export type ProductAsset = Tables<"product_assets">;
export type ProductVariant = Tables<"product_variants">;
export type ProductWardrobeLink = Tables<"product_wardrobe_links">;
export type ProviderCapability = Tables<"provider_capabilities">;
export type ProviderJob = Tables<"provider_jobs">;
export type Shot = Tables<"shots">;
export type SongAnalysis = Tables<"song_analyses">;
export type Storyboard = Tables<"storyboards">;
export type StoryboardNode = Tables<"storyboard_nodes">;
export type VideoProject = Tables<"video_projects">;

export type {
  CutType,
  StyleProfile,
  StyleProfileKind,
  TimelineItem,
  TimelineManifest,
  TimelineRenderTarget,
  TextOverlay,
} from "@/lib/timeline/types";

// Convenience: VideoProject was historically also referenced as `Project`.
export type Project = VideoProject;

// ---------- Enum aliases (Enums<...>) ----------
export type ApprovalStatus = Enums<"approval_status">;
export type AssetApprovalStatus = ApprovalStatus;
export type ArtistAssetType = Enums<"artist_asset_type">;
export type AssetType = ArtistAssetType;
export type ExportStatus = Enums<"export_status">;
export type ExportType = Enums<"export_type">;
export type ProjectAssetType = Enums<"project_asset_type">;
export type ProjectStatus = Enums<"project_status">;
export type ProductAssetRole = Enums<"product_asset_role">;
export type ProductSlot = Enums<"product_slot">;
export type ProductStatus = Enums<"product_status">;
export type PromptTemplateCategory = Enums<"prompt_template_category">;
export type ProviderJobStatus = Enums<"provider_job_status">;
export type JobStatus = ProviderJobStatus;
export type ProviderName = Enums<"provider_name">;
export type ShotPriority = Enums<"shot_priority">;
export type ShotStatus = Enums<"shot_status">;
export type ShotTransitionType = Enums<"shot_transition_type">;
export type ShotType = Enums<"shot_type">;

// ---------- Custom JSON shapes (not in Database) ----------

/**
 * Free-form artist identity profile. Stored as JSONB in
 * `artists.identity_profile_json`. All fields are optional — the UI lets the
 * user fill in whichever apply.
 */
export type ArtistLoraInfo = {
  url?: string;
  trigger?: string;
  trigger_word?: string;
};

export type ArtistIdentityProfile = {
  face?: string;
  body?: string;
  skin?: string;
  hair?: string;
  tattoos?: string;
  jewelry?: string;
  wardrobe_defaults?: string;
  distinguishing_features?: string;
  lora?: ArtistLoraInfo;
  lora_legacy_face?: ArtistLoraInfo;
  style_lora_training?: {
    status?: "pending" | "complete" | "failed";
    started_at?: string;
    completed_at?: string;
    error?: string;
    image_count?: number;
    trigger_word?: string;
    lora_url?: string;
  };
  /**
   * Locked identity photo for the canonical_base pipeline. When set, the
   * compose-look pipeline short-circuits Stage 1 and reuses this image as
   * the identity base instead of regenerating from the LoRA. Must be a
   * publicly fetchable URL (e.g. a Fal-hosted `v3b.fal.media` URL) — signed
   * Supabase URLs expire and won't work downstream on the CC backend.
   *
   * Set via the "Save as Canonical Base" button on the Look Detail page;
   * read by the AVT compose-look-proxy and forwarded to the CC backend.
   */
  canonical_base_image_url?: string | null;
};
