/**
 * Stable type-alias shim over the auto-generated Supabase `Database` type.
 *
 * `src/integrations/supabase/types.ts` is regenerated by Lovable Cloud and
 * only exports `Database` / `Json` / the `Tables<>` / `Enums<>` helpers.
 * App code historically imports named row aliases (Artist, Shot, …) and
 * enum aliases (ShotStatus, ProviderName, …) from that file. To keep the
 * codebase stable across regenerations, derive every alias here and import
 * from `@/integrations/supabase/aliases` instead.
 */
import type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json } from "./types";

export type { Database, Tables, TablesInsert, TablesUpdate, Enums, Json };

// ---------- Row aliases (Tables<...>) ----------
export type Artist = Tables<"artists">;
export type ArtistAsset = Tables<"artist_assets">;
export type CharacterFeature = Tables<"character_features">;
export type ClipReview = Tables<"clip_reviews">;
export type ExportPackage = Tables<"export_packages">;
export type GenerationFeasibility = Tables<"generation_feasibility">;
export type LocationLibrary = Tables<"location_library">;
export type ProjectAsset = Tables<"project_assets">;
export type ProjectLocationPick = Tables<"project_location_picks">;
export type ProjectPropPick = Tables<"project_prop_picks">;
export type Prompt = Tables<"prompts">;
export type PromptTemplate = Tables<"prompt_templates">;
export type PropLibrary = Tables<"prop_library">;
export type ProviderCapability = Tables<"provider_capabilities">;
export type ProviderJob = Tables<"provider_jobs">;
export type Shot = Tables<"shots">;
export type SongAnalysis = Tables<"song_analyses">;
export type Storyboard = Tables<"storyboards">;
export type StoryboardNode = Tables<"storyboard_nodes">;
export type VideoProject = Tables<"video_projects">;

// Convenience: VideoProject was historically also referenced as `Project`.
export type Project = VideoProject;

// ---------- Enum aliases (Enums<...>) ----------
export type ApprovalStatus = Enums<"approval_status">;
export type AssetApprovalStatus = ApprovalStatus;
export type ArtistAssetType = Enums<"artist_asset_type">;
export type AssetType = ArtistAssetType;
export type ExportStatus = Enums<"export_status">;
export type ExportType = Enums<"export_type">;
export type ProjectAssetType = Enums<"project_asset_type">;
export type ProjectStatus = Enums<"project_status">;
export type PromptTemplateCategory = Enums<"prompt_template_category">;
export type ProviderJobStatus = Enums<"provider_job_status">;
export type JobStatus = ProviderJobStatus;
export type ProviderName = Enums<"provider_name">;
export type ShotPriority = Enums<"shot_priority">;
export type ShotStatus = Enums<"shot_status">;
export type ShotTransitionType = Enums<"shot_transition_type">;
export type ShotType = Enums<"shot_type">;

// ---------- Custom JSON shapes (not in Database) ----------

/**
 * Free-form artist identity profile. Stored as JSONB in
 * `artists.identity_profile_json`. All fields are optional — the UI lets the
 * user fill in whichever apply.
 */
export type ArtistIdentityProfile = {
  face?: string;
  body?: string;
  skin?: string;
  hair?: string;
  tattoos?: string;
  jewelry?: string;
  wardrobe_defaults?: string;
  distinguishing_features?: string;
  [key: string]: string | undefined;
};
